Repository AY2425S2-CS2103T-W13-1/tp, pull requests merged in 2025-03, with the labels that each got.

#8 Add Tze Jen's Photo to Team Page - Issue 5
  docs/images/meatsushi64.png
Labels: type.Task, priority.High

#10 Update team's page with Wen Ting's profile photo
  docs/images/wentingchua.png
Labels: priority.High

#12 Update teams page with Shawn's info
  docs/images/shawnnygoh.png
Labels: type.Task, priority.High

#11 Update team's page with Timothy's info
  docs/images/tim0tay.png
Labels: priority.High

#18 Update AboutUs page with Shawn's details
  docs/AboutUs.md
Labels: type.Task, priority.High

#20 Update the AboutUs page with Freddie's details
  docs/AboutUs.md
Labels: priority.High

#19 Add Timothy's details to AboutUs page
  docs/AboutUs.md
Labels: priority.High

#28 Update readme
  README.md
  docs/images/Ui.png
Labels: type.Task, priority.High

#36 Update DeveloperGuide.md with Target User Profile
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#37 Update DG for user stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#41 Update DG with Use Cases
  docs/DeveloperGuide.md
Labels: priority.High

#44 Add support for the 'findtag' command
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagNamesContainsTagsPredicate.java
Labels: type.Story, priority.High

#42 Add user instructions to help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/help/local_userguide.txt
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#50 Make add contact fields optional
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#49 Add 'removetag' command
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
Labels: type.Story, priority.High

#51 Add non-functional requirements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#53 Abstract PersonDescriptor class
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/PersonDescriptor.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/AddTagPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#56 Refactor FindTagCommandParser
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
Labels: type.Enhancement, priority.High

#61 Add tests for FindTagCommand
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/person/TagNamesContainsTagsPredicateTest.java
Labels: type.Task, priority.High

#64 Add tag
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/PersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/AddTagPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonDescriptorBuilder.java
Labels: type.Enhancement, priority.High

#58 Fix test cases related to help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High

#70 Update UserGuide.md for v1.3
  docs/UserGuide.md
Labels: type.Task, priority.High

#66 Refactor tests related to AddCommand
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.High

#68 Update GUI Title and Icon
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ScoopBook.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Task, priority.High

#72 Add removeTag tests
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
Labels: priority.High

#76 Add note command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NoteWindow.java
  src/main/resources/view/NoteWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: priority.High

#75 Introduce new PersonId field for Person
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonId.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#78 Add support for the 'note' command to save new notes and edits
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/storage/FileNotesStorage.java
  src/main/java/seedu/address/storage/NotesStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NoteWindow.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/storage/FileNotesStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement, priority.High

#62 Add ExportCommand to supporting exporting of json file
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.High

#80 New UI
  build.gradle
  src/main/java/seedu/address/ui/DialogBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DialogBox.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Story, priority.Medium

#87 Edit UI UML diagram to adhere to v1.4
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/Main.java
Labels: type.Task, priority.High
