Repository AY2425S2-CS2103T-W13-1/tp, pull requests merged in 2025-04, with the labels that each got.

#90 Fix bug where notes persist after clear command
  src/main/java/seedu/address/logic/LogicManager.java
Labels: priority.High, severity.High, alpha-bug

#92 Update Storage Class Diagram to include Notes Storage
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task, priority.High

#96 Add tests for AddTagCommandParser and edits to class
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: type.Task, priority.High

#107 Add tests for FileNotesStorage
  src/test/java/seedu/address/storage/FileNotesStorageTest.java
Labels: type.Task, priority.High

#131 Note window edit
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NoteCloseInstruction.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NoteWindow.java
  src/main/java/seedu/address/ui/NoteWindowHandler.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, severity.High

#126 Add tests for PersonId, make PersonId accept positive integers only
  src/main/java/seedu/address/model/person/PersonId.java
  src/test/java/seedu/address/model/person/PersonIdTest.java
Labels: type.Task, priority.High, severity.Medium

#127 Fix UI display for optional fields
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Task

#141 Update addtag section to clarify tag case-sensitivity
  docs/UserGuide.md
Labels: type.Task, priority.High

#108 Update UG with import and export commands
  docs/UserGuide.md
Labels: priority.High

#136 Refactor FindTagCommandParser to increase code coverage and testability
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Labels: type.Task, priority.Medium

#152 Update UG and DG
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: type.Task, priority.Medium

#151 Update add in UG to specify name and tag alphanumeric restrictions
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#154 Update remove tag
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
  src/main/java/seedu/address/logic/parser/RemoveTagCommandParser.java
  src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java
  src/test/java/seedu/address/logic/parser/RemoveTagCommandParserTest.java
Labels: priority.High, alpha-bug

#234 Remove 'Archiving data files' section
  docs/UserGuide.md
Labels: type.Task, priority.High

#228 Edit dg parts
  docs/DeveloperGuide.md
Labels: developer-guide

#236 Update UG for clarity and consistency in behaviour
  docs/UserGuide.md
Labels: user-guide

#237 Update DG and UG for validity of name and planned enhancements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: user-guide, developer-guide

#242 Update FAQ in User Guide with Duplicate Contacts
  docs/UserGuide.md
Labels: priority.High
